#You can add more directories here by typing them one per line or using the bash command (work in progress)

#You must restart the service for changes to take effect 'systemctl --user restart appimage-linker.service'

DIRS=(
    "$HOME/AppImages"
)